require "spec_helper"
require "active_record"

RSpec.describe ArchiveHook do
  it "has a version number" do
    expect(ArchiveHook::VERSION).not_to be nil
  end

  class Board < ActiveRecord::Base
  end

  class Card < ActiveRecord::Base
    belongs_to :board
  end

  class Tag < ActiveRecord::Base
    belongs_to :card
  end

  class CamelBoard < ActiveRecord::Base
    self.table_name = "CamelBoards"
  end

  class CamelCard < ActiveRecord::Base
    self.table_name = "CamelCards"
  end

  before(:all) do
    database = 'archive_hook_test'
    Kernel.system("createdb", database)
    ActiveRecord::Base.establish_connection(adapter: "postgresql", database: database)
    ActiveRecord::Base.connection.execute <<-SQL
      create table boards (
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
        title varchar,
        "default" boolean,
        "order" integer,
        "position" integer,
        created_at timestamp
      );
      create table cards (
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
        title varchar, 
        board_id integer,
        created_at timestamp,
        foreign key (board_id) REFERENCES boards
      );
      create table tags (
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
        title varchar, 
        card_id integer,
        created_at timestamp,
        foreign key (card_id) REFERENCES cards
      );
      create table "CamelBoards" (
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        title varchar,
        "createdAt" timestamp,
        "position" integer,
        "default" boolean,
        "order" integer,
        created_at timestamp
      );
      create table "CamelCards" (
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        title varchar,
        "CamelBoard_id" integer,
        camel_board_id integer,
        "group" varchar,
        created_at timestamp
      );
      create table "CamelBoards_archive" (like "CamelBoards");
      create table "CamelCards_archive" (like "CamelCards");
      create table boards_archive (like boards);
      create table cards_archive (like cards);
      create table tags_archive (like tags);
    SQL
  end

  after(:each) do
    ActiveRecord::Base.connection.execute <<-SQL
      delete from tags;
      delete from tags_archive;
      delete from cards;
      delete from cards_archive;
      delete from boards;
      delete from boards_archive;
      delete from "CamelCards";
      delete from "CamelCards_archive";
      delete from "CamelBoards";
      delete from "CamelBoards_archive";
    SQL
  end

  after(:all) do
    ActiveRecord::Base.connection.disconnect!
    database = 'archive_hook_test'
    Kernel.system('dropdb', database)
  end

  let(:mapping) { { Board => { children: [Card] }, Card => { children: [Tag] } } }
  let!(:actual_board) { Board.create(title: "Current issues") }
  let!(:actual_card) { Card.create(title: "Create game", board: actual_board) }
  let!(:actual_tag) { Tag.create(title: "r1", card: actual_card) }

  describe ".archive" do
    subject { described_class.archive(Board, 1.day.ago, mapping) }

    context "when everything is actual" do
      it "doesn't clear" do
        expect { subject }.to not_change { Board.count }.from(1)
      end
    end

    context "when there is something outdated" do
      let!(:still_actual_board) { Board.create(title: "Still actual") }
      let!(:not_actual_card) { Card.create(title: "Not actual card", board: still_actual_board, created_at: 2.days.ago) }
      let!(:not_actual_tag) { Tag.create(title: "r2", card: not_actual_card, created_at: 2.days.ago) }

      let!(:outdated_board) { Board.create(title: "Outdated board", created_at: 2.days.ago) }
      let!(:outdated_card) { Card.create(title: "Outdated card", board: outdated_board, created_at: 2.days.ago) }
      let!(:outdated_tag) { Tag.create(title: "r3", card: outdated_card, created_at: 2.days.ago) }

      it "archives only root and their related objects" do
        expect { subject }.to change { Board.count }.by(-1).and change { Card.count }.by(-1).and change { Tag.count }.by(-1)
      end

      context "default scope" do
        before(:all) do
          class Card
            default_scope { where("1=0") }
          end
        end

        after(:all) do
          class Card
            default_scope { unscoped }
          end
        end

        it "archives them" do
          expect { subject }.to change { Board.count }.by(-1)
                            .and change { Board.from("boards_archive").count }.by(1)
                            .and change { Card.unscoped.count }.by(-1)
                            .and change { Card.unscoped.from("cards_archive").count }.by(1)
        end
      end
    end

    context "when archive column is not created_at" do
      let(:mapping) { { Board => { children: [Card], column: :published_at } } }
      let!(:outdated_board) { Board.create(title: "Archive board", created_at: 2.days.ago, published_at: Time.current) }
      let!(:outdated_card) { Card.create(title: "Archive card", board: outdated_board, created_at: 2.days.ago) }

      before(:all) do
        ActiveRecord::Base.connection.execute <<-SQL
          alter table boards add column published_at timestamp;
          alter table boards_archive add column published_at timestamp;
        SQL
        Board.reset_column_information
      end

      it "doesn't archive" do
        expect { subject }.to not_change { Board.count }.from(2).and not_change { Card.count }
      end

      context "and archive date column is suitable" do
        before(:each) do
          outdated_board.update_attribute(:published_at, 2.days.ago)
        end

        it "archives them" do
          expect { subject }.to change { Board.count }.by(-1).and change { Card.count }.by(-1)
        end
      end
    end

    context "when there are missing relations in the mapping" do
      let(:mapping) { { Board => { children: [Card] } } }
      let!(:outdated_board) { Board.create(title: "Outdated board", created_at: 2.days.ago) }
      let!(:outdated_card) { Card.create(title: "Outdated card", board: outdated_board, created_at: 2.days.ago) }
      let!(:outdated_tag) { Tag.create(title: "r1", card: outdated_card, created_at: 2.days.ago) }

      it "doesn't archive" do
        expect { subject }.to raise_error(ActiveRecord::ActiveRecordError).and not_change { Board.count }
      end
    end
  end

  describe ".archive_scope" do
    subject { described_class.archive_scope(Board.where(id: ids), mapping) }
    let!(:outdated_board) { Board.create(title: "Archive board", created_at: 2.days.ago) }
    let!(:outdated_card) { Card.create(title: "Archive card", created_at: 2.days.ago) }
    let!(:outdated_tag) { Tag.create(title: "r2", created_at: 2.days.ago) }

    context "when everything is actual" do
      let(:ids) { 0 }

      it "doesn't clear" do
        expect { subject }.to not_change { Board.count }.from(2)
      end
    end

    context "when there are items to archive" do
      let(:ids) { actual_board.id }

      it "archives them" do
        expect { subject }.to change { Board.count }.by(-1)
                          .and change { Board.from("boards_archive").count }.by(1)
                          .and change { Card.count }.by(-1)
                          .and change { Card.from("cards_archive").count }.by(1)
                          .and change { Tag.count }.by(-1)
                          .and change { Tag.from("tags_archive").count }.by(1)
      end
    end
  end

  describe "mixed case identifiers" do
    # Postgres folds unquoted identifiers to lower case, so a CamelCase table or
    # column only resolves when it is quoted -- an unquoted "CamelBoards" is
    # looked up as camelboards and reported as not existing.
    let(:mapping) { { CamelBoard => { children: [CamelCard] } } }
    let!(:board) do
      CamelBoard.create(title: "Mixed case", created_at: 2.days.ago)
                .tap { |r| r.update_columns("createdAt" => Time.now, "position" => 3, "default" => true, "order" => 1) }
    end

    it "archives a CamelCase table with CamelCase and reserved word columns" do
      expect { described_class.archive_scope(CamelBoard.where(id: board.id), mapping) }
        .to change { CamelBoard.count }.by(-1)
        .and change { CamelBoard.from('"CamelBoards_archive" as "CamelBoards"').count }.by(1)
    end

    it "restores it with every column value intact" do
      described_class.archive_scope(CamelBoard.where(id: board.id), mapping)
      described_class.restore_scope(CamelBoard.where(id: board.id), mapping)

      restored = CamelBoard.find(board.id)
      expect(restored["position"]).to eq(3)
      expect(restored["default"]).to be(true)
      expect(restored["order"]).to eq(1)
      expect(restored["createdAt"]).to be_present
    end
  end

  describe "reserved word columns" do
    let(:mapping) { { Board => { children: [Card] } } }
    let!(:board) do
      Board.create(title: "Quoting", created_at: 2.days.ago).tap do |record|
        record.update_columns("default" => true, "order" => 7, "position" => 9)
      end
    end

    it "archives a table whose columns collide with SQL keywords" do
      expect { described_class.archive_scope(Board.where(id: board.id), mapping) }
        .to change { Board.count }.by(-1)
        .and change { Board.from("boards_archive").count }.by(1)
    end

    it "restores it with the column values intact" do
      described_class.archive_scope(Board.where(id: board.id), mapping)
      described_class.restore_scope(Board.where(id: board.id), mapping)

      restored = Board.find(board.id)
      expect(restored["default"]).to be(true)
      expect(restored["order"]).to eq(7)
      expect(restored["position"]).to eq(9)
    end
  end

  describe ".dearchive_scope" do
    subject { described_class.restore_scope(Board.where(id: ids), mapping) }
    let!(:outdated_board) { Board.create(title: "Archive board", created_at: 2.days.ago) }
    let!(:outdated_card) { Card.create(title: "Archive card", created_at: 2.days.ago) }
    let!(:outdated_tag) { Tag.create(title: "r2", created_at: 2.days.ago) }

    before(:each) do
      described_class.archive_scope(Board.where(id: actual_board.id), mapping)
    end

    context "when everything is actual" do
      let(:ids) { 0 }

      it "doesn't clear" do
        expect { subject }.to not_change { Board.count }.from(1)
      end
    end

    context "when there are items to dearchive" do
      let(:ids) { actual_board.id }

      it "dearchives them" do
        expect { subject }.to change { Board.count }.by(1)
                          .and change { Board.from("boards_archive").count }.by(-1)
                          .and change { Card.count }.by(1)
                          .and change { Card.from("cards_archive").count }.by(-1)
                          .and change { Tag.count }.by(1)
                          .and change { Tag.from("tags_archive").count }.by(-1)
      end
    end
  end
end
